name: flutter_objectbox_riverpod_sample_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  objectbox: ^1.6.2
  objectbox_flutter_libs: ^1.6.2
  flutter_riverpod: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.0.0 
  freezed:
  objectbox_generator:

flutter:
  uses-material-design: true
